on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar dependências desatualizadas
        uses: dependabot/dependabot-core@v0.160.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          package_manager: "all"

  codeql-analise:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Inicializar o CodeQL
        uses: github/codeql-action/init@v1

      - name: Construir e analisar
        uses: github/codeql-action/analyze@v1

  segredos:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar segredos
        uses: actions/secret-checker@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_secrets: true
          paths: '.'

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar o SonarQube
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          scannerVersion: '4.6'

  horusec:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Horusec
        uses: horusit/horusec-action@v2
        with:
          horusec_version: 'v2'
          horusec_additional_flags: '--json-output'

